package pvz.view;

public enum MenuType{
    SIGNUP_MENU, GAME_MENU, CHAPTER_MENU, COLLECTION_MENU, GREENHOUSE_MENU, LOGIN_MENU, MAIN_MENU, NETWORK_MENU, NEWS_MENU, PROFILE_MEMU, QUEST_MENU, SETTINGS_MENU, TRAVEL_LOG_MENU;
}
