package pvz.model.entities.zombies;

public enum AnciantEgyptZombies implements ZombieType {
    ZOMBIE_MUMMY_DEFAULT, ZOMBIE_MUMMY_ARMOR1DEFAULT, ZOMBIE_MUMMY_ARMOR2DEFAULT,
        ZOMBIE_MUMMY_ARMOR4DEFAULT, ZOMBIE_PHARAOH_DEFAULT, ZOMBIE_RA_DEFAULT,
        ZOMBIE_EXPLORER_DEFAULT, ZOMBIE_TOMB_RAISER_DEFAULT, ZOMBIE_CAMEL_DEFAULT,
        ZOMBIE_EGYPT_GARGANTUAR , ZOMBIE_EGYPT_IMP_DEFAULT, ZOMBIE_ZOMBOSS_MECH_EGYPT;
}
