package pvz.model.entities.zombies;

public enum BigWaveBeachZombies implements ZombieType{
    ZOMBIE_BEACH_DEFAULT,ZOMBIE_BEACH_ARMOR1_DEFAULT
    ,ZOMBIE_BEACH_ARMOR2DEFAULT,ZOMBIE_BEACH_SNORKEL
    ,ZOMBIE_BEACH_SURFER,ZOMBIE_BEACH_FISHERMAN,
    ZOMBIE_BEACH_OCTOPUS,ZOMBIE_BEACH_GARGANTUAR,
    ZOMBIE_BEACH_IMP_DEFAULT , ZOMBIE_BEACH_FASTSWIMMER, ZOMBIE_ZOMBOSS_MECH_PIRATE ;
}
