package pvz.model.entities.zombies;

public enum DarkAgesZombies implements ZombieType {
    ZOMBIE_DARK_DEFAULT,ZOMBIE_DARK_ARMOR1_DEFAULT
    , ZOMBIE_DARK_ARMOR2DEFAULT, ZOMBIE_DARK_ARMOR3DEFAULT
    , ZOMBIE_DARK_ARMOR4DEFAULT, ZOMBIE_WIZARD_DEFAULT
    , ZOMBIE_DARK_JUGGLER_DEFAULT, ZOMBIE_DARK_KING
    , ZOMBIE_DARK_GARGANTUAR , ZOMBIE_DARK_IMP_DEFAULT, ZOMBIE_ZOMBOSS_MECH_DARK;
    }
