package pvz.model.entities.zombies;

public enum FrostbiteCaveZombies implements ZombieType{
    ZOMBIE_ICEAGE_DEFAULT, ZOMBIE_ICEAGE_ARMOR1DEFAULT, ZOMBIE_ICEAGE_ARMOR2DEFAULT,
    ZOMBIE_ICEAGE_ARMOR3DEFAULT, ZOMBIE_ICEAGE_HUNTER, ZOMBIE_ICEAGE_TROGLOBITE,
    ZOMBIE_ICE_AGEDODO, ZOMBIE_WEASELHOARDER_DEFAULT, ZOMBIE_WEASEL_DEFAULT,
    ZOMBIE_ICEAGE_GARGANTUAR, ZOMBIE_ICEAGE_IMP_DEFAULT, ZOMBIE_ZOMBOSS_MECH_COWBOY;
}
